EmmyLuaLs/emmylua-analyzer-rust

crates/code_analysis/src/compilation/analyzer/doc/infer_type.rs, crates/code_analysis/src/db_index/type/humanize_type.rs, crates/code_analysis/src/db_index/type/types.rs, crates/code_analysis/src/semantic/type_compact/mod.rs, crates/emmylua_doc_cli/src/markdown_generator/render.rs, crates/emmylua_ls/src/handlers/completion/providers/type_special_provider.rs, crates/emmylua_ls/src/handlers/hover/hover_humanize.rs
Fix typos in hover and inline parameter type displays:
=> fix typo: interger → integer

crates/emmylua_ls/src/context/mod.rs, crates/emmylua_ls/src/context/status_bar.rs, crates/emmylua_ls/src/handlers/initialized/mod.rs
The current progress notifications are only fit for VSCode, but we can use the LSP $/progress method to notify for progress which will work for any LSP clients that use the method.
=> feat: add progress notifications

crates/code_analysis/src/config/mod.rs
This change allows this config to work:
```json
"workspace": {
"library": [
"/opt/homebrew/opt/neovim/share/nvim/runtime",
"/opt/homebrew/opt/lua-language-server/libexec/meta/3rd/luassert/library",
"/opt/homebrew/opt/lua-language-server/libexec/meta/3rd/luv/library",
"/Users/dsully/.local/share/nvim/lazy/lazy.nvim/lua",
"/Users/dsully/.local/share/nvim/lazy/snacks.nvim/lua",
"/Users/dsully/.local/share/nvim/lazy/which-key.nvim/lua"
]
}
```
=> Allow absolute paths to be used by removing unneeded branch that checks for '/'

.github/workflows/build.yml
This patch bumps `actions/upload-artifact@v3` to `actions/upload-artifact@v4`. Now `v3` is deprecated [^1] which turned out to break #9.
[^1] https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> bump upload artifact action to v4

.github/workflows/build.yml, CHANGELOG.md, crates/code_analysis/src/semantic/instantiate/tpl_pattern.rs
This patch adds simple type level matching for the doc functions and signatures allowing to instantiate generics based on the passed functions.
The following code demonstrates a generic type instantiated by this feature.
```lua
---@param a number
---@return string
local function tostr(a)
return tostring(a)
end
---@generic T, U
---@param x T
---@param f fun(x: T): U
---@return U
local function apply(x, f)
return f(x)
end
--"a" is inferred as a string.
a = apply(3, tostr)
```
=> instantiate generics using the passed functions

CHANGELOG.md, crates/emmylua_ls/src/handlers/initialized/client_config/neovim_config.rs
This patch fixes loading configurations in NeoVim in cases when no extra
LSP config parameters are provided. After loading Emmyrc configs
they were merged with partial Emmyrcs loaded based on the LSP config
in NeoVim. If LSP hasn't got configuration section configured you came
into a situation with only Null object partial Emmyrc overwriting
the local Emmyrc configuration.
Let's ignore Null LSP configurations (i.e. unprovided ones) to prevent
them from completely overwriting other configurations when loading
NeoVim LSP configuration options.
=> fix loading configurations in NeoVim

CHANGELOG.md, crates/code_analysis/src/db_index/type/humanize_type.rs
This patch extends the humanized variant of the const table. Previously, every constant table has been displayed as `table`. This patch makes short constant tables (having full type name no more than 36 symbols length) humanize into preciser types. See the following examples.
```lua
-- a is humanized like `{ [1] = "test", [3] = 4 }`
local a = { [1] = 'test', [3] = 4 }
-- b is humanized like `{ name = "Pete", age = 36 }`
local b = { name = 'pete', age = 36 }
-- c is humanized like `{ a = table }`
local c = { a = { very_very_very_very_very_long = 10000 } }
-- d is humanized like `table`
local d = { very_very_very_very_very_long = 10000 }
```
=> extend const table type humanization

CHANGELOG.md, crates/emmylua_ls/src/handlers/completion/add_completions/add_member_completion.rs, crates/emmylua_ls/src/handlers/completion/providers/mod.rs, crates/emmylua_ls/src/handlers/completion/providers/table_decl_field_provider.rs
This patch adds basic autocompletion features for table field names when declaring a table.
Example.
```lua
---@class Bar: table
---@field buz number
---@param a Bar
local function foo(a)
end
foo({
-- `buz` field is suggested here...
})
```
The implementation is very basic. Known limitations are the following.
* The field names are suggested only when the table is instantiated within the function arguments with defined types.
* Generics/inferred funkjction types aren't supported yet.
Closes #20
=> add basic table field names autocompletion

CHANGELOG.md, crates/emmylua_code_analysis/src/semantic/infer/infer_binary.rs
This patch fixes possible LSP panic that occurs when LSP type inferer power calculations overflowed the `i64` value upper bound.
The fix is straightforward: replace the `pow()` call that may throw an exception with safe `checked_pow()`.
=> fix possible panic when calculating pow values

CHANGELOG.md, crates/emmylua_check/src/init.rs
This patch adds support for `workspace.library` option in check tool. The directory is loaded with the same code used within the language server. The implementation is very straightforward and is subject to change.
=> add support for `workspace.library` in check tool

CHANGELOG.md, crates/emmylua_code_analysis/src/semantic/type_compact/mod.rs
This patch adds support for comparing array and tuple types. Basically, the code just asserts every element of a tuple is just the same as the array element when casting `tuple -> array`.
```lua
---@param a number[]
local function test(a) end
---@type [number, number]
local foo = {1, 2}
---@type [number, string]
local bar = {1, 'test'}
test(foo) -- OK
test(bar) -- Not OK
```
Note that the allowed conversions doesn't work in the `array -> tuple` direction.
```lua
---@param a [number, number]
local function test2(a) end
---@type number[]
local buz = {1, 2}
-- A warning is thrown, likely this is a mistake since the length of the
-- array is arbitrary.
test2(buz)
```
=> support array and tuple compatibility comparison

CHANGELOG.md, crates/emmylua_ls/src/handlers/completion/add_completions/add_member_completion.rs
This patch adds completions for functions overloads. Basically it just adds extra function signatures.
For instance, when you write `table.ins...` you receive the following completions.
```
insert FUNCTION (list, pos, value)number
insert FUNCTION (list, value)number
```
=> add function overload completions

crates/emmylua_code_analysis/resources/std/global.lua
With this change: 
```lua
local a = tonumber(1) -- number
local b = tonumber('1') -- (number|nil)
local c = tonumber(nil) -- nil
local d = tonumber({}) -- nil
local e = tonumber('1', 10) -- (number|nil)
local f = tonumber(nil, 10) -- nil
local g = tonumber(1, 10) -- number
```
Quite possible that there's some redundant ones and/or can be improved further
=> improve annotations for tonumber()

crates/emmylua_code_analysis/src/db_index/signature/signature.rs, crates/emmylua_code_analysis/src/diagnostic/checker/missing_return_value.rs, crates/emmylua_code_analysis/src/diagnostic/checker/param_type_check.rs, crates/emmylua_code_analysis/src/diagnostic/checker/redundant_return_value.rs, crates/emmylua_code_analysis/src/diagnostic/checker/return_type_mismatch.rs, crates/emmylua_code_analysis/src/diagnostic/test/param_type_check_test.rs, crates/emmylua_code_analysis/src/diagnostic/test/redundant_return_value_test.rs, crates/emmylua_code_analysis/src/diagnostic/test/return_type_mismatch_test.rs, crates/emmylua_code_analysis/src/semantic/mod.rs, crates/emmylua_code_analysis/src/semantic/type_check/mod.rs, crates/emmylua_parser/src/syntax/node/lua/expr.rs
=> diagnostic: fix

CHANGELOG.md, crates/emmylua_code_analysis/src/compilation/analyzer/lua/stats.rs, crates/emmylua_code_analysis/src/compilation/test/for_range_var_infer_test.rs, crates/emmylua_code_analysis/src/compilation/test/mod.rs
This patch adds support for deriving for-range loop variables from the
iterator types specified as aliases and class overloads.
I.e. you may alias `fun(v: any): K, V` and if you try to iterate through
the instance of this type the loop variables will be inferred as `K, V`.
If the class provide a function overload it's also used for type
inference.
It might be helpful for writing complex functional libraries for
determining custom iterators.
Example.
```lua
---@alias foo (fun(tbl: any): (number, integer))
---@class bar
---@overload fun(tbl: any): (number, integer)
---@type foo
local b = {}
---@type bar
local c = {}
for k, v in b do
-- k is inferred as number
-- v is inferred as string
end
for k, v in c do
-- k is also inferred as number
-- v is also inferred as string
end
```
=> infer for range vars from aliases and overloads

crates/emmylua_ls/src/handlers/initialized/client_config/neovim_config.rs
`scopeUri` is expected by lazydev.nvim
the `clone`-ing of workspace folders and `unwrap()` could be re-worked, but it works (as long as lazydev does its part, which isn't the case rn)
xref https://github.com/folke/lazydev.nvim/issues/86
=> Support lazydev.nvim

crates/emmylua_code_analysis/locales/lint.yml, crates/emmylua_code_analysis/resources/schema.json, crates/emmylua_code_analysis/src/db_index/type/types.rs, crates/emmylua_code_analysis/src/diagnostic/checker/mod.rs, crates/emmylua_code_analysis/src/diagnostic/checker/unnecessary_assert.rs, crates/emmylua_code_analysis/src/diagnostic/lua_diagnostic_code.rs
Warns on unnecessary assertions (on expressions that always evaluate to `true`):
I might need help with tests and i18n. Also, this does not work for aliases, I couldn't figure out why:
=> Diagnostics for unnecessary assert

crates/emmylua_code_analysis/src/diagnostic/checker/access_invisible.rs, crates/emmylua_code_analysis/src/diagnostic/checker/analyze_error.rs, crates/emmylua_code_analysis/src/diagnostic/checker/assign_type_mismatch.rs, crates/emmylua_code_analysis/src/diagnostic/checker/await_in_sync.rs, crates/emmylua_code_analysis/src/diagnostic/checker/check_field.rs, crates/emmylua_code_analysis/src/diagnostic/checker/check_param_count.rs, crates/emmylua_code_analysis/src/diagnostic/checker/check_return_count.rs, crates/emmylua_code_analysis/src/diagnostic/checker/circle_doc_class.rs, crates/emmylua_code_analysis/src/diagnostic/checker/code_style_check.rs, crates/emmylua_code_analysis/src/diagnostic/checker/deprecated.rs, crates/emmylua_code_analysis/src/diagnostic/checker/discard_returns.rs, crates/emmylua_code_analysis/src/diagnostic/checker/duplicate_require.rs, crates/emmylua_code_analysis/src/diagnostic/checker/duplicate_type.rs, crates/emmylua_code_analysis/src/diagnostic/checker/incomplete_signature_doc.rs, crates/emmylua_code_analysis/src/diagnostic/checker/local_const_reassign.rs, crates/emmylua_code_analysis/src/diagnostic/checker/missing_fields.rs, crates/emmylua_code_analysis/src/diagnostic/checker/mod.rs, crates/emmylua_code_analysis/src/diagnostic/checker/need_check_nil.rs, crates/emmylua_code_analysis/src/diagnostic/checker/param_type_check.rs, crates/emmylua_code_analysis/src/diagnostic/checker/redefined_local.rs, crates/emmylua_code_analysis/src/diagnostic/checker/return_type_mismatch.rs, crates/emmylua_code_analysis/src/diagnostic/checker/syntax_error.rs, crates/emmylua_code_analysis/src/diagnostic/checker/unbalanced_assignments.rs, crates/emmylua_code_analysis/src/diagnostic/checker/undefined_doc_param.rs, crates/emmylua_code_analysis/src/diagnostic/checker/undefined_global.rs, crates/emmylua_code_analysis/src/diagnostic/checker/unnecessary_assert.rs, crates/emmylua_code_analysis/src/diagnostic/checker/unused.rs
This commit makes it so that diagnostic checkers no longer have to define magic public variables which will be called by a macro. Instead, they all implement a common trait which will easily enforce that all the checking data is defined. This also means compile errors will be quicker and more understandable.
=> Refactor: migrate diagnostics to use trait rather than macro

crates/emmylua_code_analysis/locales/lint.yml, crates/emmylua_code_analysis/resources/std/coroutine.lua, crates/emmylua_code_analysis/resources/std/debug.lua, crates/emmylua_code_analysis/resources/std/os.lua, crates/emmylua_code_analysis/resources/std/table.lua, crates/emmylua_code_analysis/src/compilation/analyzer/decl/docs.rs, crates/emmylua_code_analysis/src/db_index/module/mod.rs, crates/emmylua_code_analysis/src/db_index/type/type_decl.rs, crates/emmylua_code_analysis/src/diagnostic/checker/duplicate_type.rs, crates/emmylua_code_analysis/src/diagnostic/checker/return_type_mismatch.rs, crates/emmylua_code_analysis/src/diagnostic/test/missing_parameter_test.rs, crates/emmylua_code_analysis/src/diagnostic/test/return_type_mismatch_test.rs, crates/emmylua_code_analysis/src/semantic/overload_resolve/mod.rs
=> diagnostic

crates/emmylua_code_analysis/resources/std/global.lua, crates/emmylua_code_analysis/resources/std/io.lua, crates/emmylua_code_analysis/resources/std/math.lua, crates/emmylua_code_analysis/resources/std/os.lua, crates/emmylua_code_analysis/resources/std/package.lua, crates/emmylua_code_analysis/resources/std/string.lua
Not sure why these were added, but they shouldn't be necessary.
=> fix: stdlib remove some overloads

crates/emmylua_code_analysis/resources/std/debug.lua
- Removed `debug.infoWhat` since the `what` argument can contain multiple characters, e.g. `'Sl'`.
- Added `@nodiscard` to several functions.
- Fixed `debug.getlocal`.
=> fix(std): debug.lua

crates/emmylua_code_analysis/resources/std/math.lua
`math.floor(math.huge) == math.huge` so should define it as an integer.
=> fix(std): define math.huge as integer

CHANGELOG.md, Cargo.lock, crates/emmylua_ls/Cargo.toml, crates/emmylua_ls/src/context/workspace_manager.rs, docs/config/emmyrc_json_EN.md
This patch adds support for setting up a global configuration for the language server.
This can be done in a various ways.
* Via `<os-specific home dir>/[.emmyrc.json|.luarc.json]`.
* Via `<os-specific config dir>/emmylua_ls/[.emmyrc.json|.luarc.json]`.
* By setting enviroment EMMYLUALS_CONFIG environment variable with a path to the desired JSON config.
This config files have less priority than the local ones.
=> Allow providing LSP configurations globally

crates/emmylua_code_analysis/locales/lint.yml, crates/emmylua_code_analysis/src/compilation/analyzer/unresolve/resolve_closure.rs, crates/emmylua_code_analysis/src/compilation/test/closure_param_infer_test.rs, crates/emmylua_code_analysis/src/compilation/test/metatable_test.rs, crates/emmylua_code_analysis/src/diagnostic/checker/check_field.rs, crates/emmylua_code_analysis/src/diagnostic/checker/return_type_mismatch.rs, crates/emmylua_code_analysis/src/diagnostic/test/param_type_check_test.rs, crates/emmylua_code_analysis/src/diagnostic/test/undefined_field_test.rs, crates/emmylua_code_analysis/src/resources/mod.rs, crates/emmylua_code_analysis/src/semantic/infer/infer_call/infer_setmetatable.rs, crates/emmylua_code_analysis/src/semantic/infer/infer_index.rs, crates/emmylua_code_analysis/src/semantic/type_check/simple_type.rs, crates/emmylua_ls/src/handlers/code_actions/actions/build_disable_code.rs, crates/emmylua_ls/src/handlers/code_actions/actions/mod.rs, crates/emmylua_ls/src/handlers/code_actions/build_actions.rs, crates/emmylua_ls/src/handlers/command/commands/emmy_disable_code.rs, crates/emmylua_ls/src/handlers/completion/providers/doc_name_token_provider.rs, crates/emmylua_ls/src/handlers/completion/providers/mod.rs, crates/emmylua_ls/src/handlers/completion/test/completion_test.rs, crates/emmylua_ls/src/handlers/hover/mod.rs, crates/emmylua_ls/src/handlers/semantic_token/build_semantic_tokens.rs, crates/emmylua_ls/src/handlers/signature_helper/build_signature_helper.rs, crates/emmylua_ls/src/handlers/signature_helper/signature_helper_builder.rs
fixes #348 
fixes #350 
fixes #345
fixes #351
fixes #299
=> optimize && fix

crates/emmylua_code_analysis/resources/schema.json, crates/emmylua_code_analysis/src/config/configs/strict.rs, crates/emmylua_code_analysis/src/diagnostic/test/unnecessary_assert_test.rs, crates/emmylua_code_analysis/src/semantic/infer/infer_index.rs, docs/config/emmyrc_json_CN.md, docs/config/emmyrc_json_EN.md
Expressions like this:
```lua
---@type integer[]
local arr = {1, 2, 3}
return arr[2]
```
should be considered as type `integer|nil`, since array accesses can always *potentially* return `nil`. This commit marks those expressions as such.
Related to #248
=> feat: treat array index as nil-able

crates/emmylua_code_analysis/locales/lint.yml, crates/emmylua_code_analysis/src/diagnostic/checker/unnecessary_assert.rs, crates/emmylua_code_analysis/src/diagnostic/test/unnecessary_assert_test.rs
This is the reverse of unnecessary assertions; these are assertions that will always fail (and will be equivalent to just `error()`)
=> feat: diagnostics for "impossible" assertions

crates/emmylua_ls/src/handlers/definition/goto_def_definition.rs, crates/emmylua_ls/src/handlers/definition/mod.rs, crates/emmylua_ls/src/handlers/definition/test/definition_test.rs, crates/emmylua_ls/src/handlers/definition/test/mod.rs, crates/emmylua_ls/src/handlers/test_lib/mod.rs
当函数调用参数为string且目标为字符串泛型模板时, 允许跳转到实际定义
=> feature: add goto_str_tpl_ref_definition

crates/emmylua_code_analysis/resources/std/global.lua
This pull request updates the type annotations for the `next` function in the `global.lua` file to improve type safety and provide better support for generic types.
Enhancements to type annotations:
* [`crates/emmylua_code_analysis/resources/std/global.lua`](diffhunk://#diff-d8e6f1c80026123f91eb74db8925ca9f651bee0d1ef114e95ff80279538f5c8dL217-R221): Updated the `next` function's annotations to use generics (`K, V`) for key-value pairs, allowing more precise type inference. The `table` parameter now supports `table<K, V>`, `V[]`, and `{[K]: V}` types, and the return type reflects the generic key-value pair (`K?, V?`).
=> Enhance `next` function type annotations with generics and overloads 🌟✨

crates/emmylua_code_analysis/resources/std/global.lua
Note Lua allows:
```lua
setmetable({}, nil)
```
but does not allow:
```lua
setmetable({})
```
=> std: allow setmetable to take `nil`

crates/emmylua_doc_cli/src/cmd_args.rs, crates/emmylua_doc_cli/src/init.rs, crates/emmylua_doc_cli/src/main.rs
我的项目，只有个别目录，需要生成文档，所以不希望传根目录到 input 参数。
把目录添加到 .emmyrc.json 的 library 字段应该也可以，但 input 又是必填的，索性 input 也支持多个值。
=> emmylua_doc_cli: 支持多个input

crates/emmylua_doc_cli/src/json_generator/export.rs, crates/emmylua_doc_cli/src/json_generator/json_types.rs
- Export generics for aliases and enums,
- Export `emmyrc` config so that documentation generators can have access to properties like `classDefaultCall`.
=> Add more info to json docs export

rust-toolchain.toml
**Issue:**
When working in different rust projects, they can use different toolchains such as stable or nightly. This can lead to issues when trying to build or run the project if the wrong toolchain is used.
**Solution:**
Add a `rust-toolchain.toml` file to the project to specify the correct toolchain. This can allow tools like `rustup` to automatically switch to the correct toolchain when entering the project directory.
https://ianwwagner.com/til/rust-toolchain-toml
=> chore: add rust-toolchain.toml to autopick correct toolchain

crates/emmylua_code_analysis/src/config/config_loader.rs, crates/emmylua_code_analysis/src/config/mod.rs, crates/emmylua_ls/src/handlers/command/commands/emmy_add_doc_tag.rs, crates/emmylua_ls/src/handlers/command/commands/emmy_disable_code.rs
Right now, `disable_code` and `add_doc_tag` commands load `.emmyrc.json` into an `EmmyRc` object, change it, and then write it back. This results in serialization of all possible fields, even those that were missing in the
original JSON file.
This behaviour might cause an issue if these newly serialized fields shadow those configured in a global `.emmyrc.json`.
This PR changes edit logic to avoid creating full `EmmyRc` object. Instead, it parses `.emmyrc.json` into a `Value`, modifies it directly, and dumps it back. This way, only fields requested by the user are injected, and nothing else.
=> Don't add default fields when automatically editing `.emmyrc.json`

crates/emmylua_code_analysis/resources/schema.json, crates/emmylua_code_analysis/src/config/configs/code_action.rs, crates/emmylua_code_analysis/src/config/configs/codelen.rs, crates/emmylua_code_analysis/src/config/configs/completion.rs, crates/emmylua_code_analysis/src/config/configs/diagnostics.rs, crates/emmylua_code_analysis/src/config/configs/document_color.rs, crates/emmylua_code_analysis/src/config/configs/hover.rs, crates/emmylua_code_analysis/src/config/configs/inlayhint.rs, crates/emmylua_code_analysis/src/config/configs/inline_values.rs, crates/emmylua_code_analysis/src/config/configs/mod.rs, crates/emmylua_code_analysis/src/config/configs/references.rs, crates/emmylua_code_analysis/src/config/configs/semantictoken.rs, crates/emmylua_code_analysis/src/config/configs/workspace.rs, crates/emmylua_code_analysis/src/config/mod.rs
This is used with EmmyLua/VSCode-EmmyLua#242.
=> Add annotations for exporting VSCode settings

crates/emmylua_code_analysis/src/db_index/module/mod.rs
Fixes #683.
note: I've also solved this in lux by not adding the project root to the workspaces, but instead adding the `lua` and `src` directories, if they exist.
Still, this fix could be useful in case someone else runs into this problem.
=> fix: don't add libraries in subdirectories to the main workspace

crates/emmylua_ls/src/handlers/hover/mod.rs, crates/emmylua_ls/src/handlers/test/hover_test.rs
Fixes an issue with hover behavior on dot selectors. When the cursor was placed to the left of the dot (e.g., `struct|.field`), the hover would incorrectly show information for the field and highlight the dot token.
Before/After:
=> fix(hover): use left token when cursor is before '.', ':', '[', ']'

crates/emmylua_code_analysis/src/compilation/mod.rs, crates/emmylua_code_analysis/src/semantic/mod.rs, crates/emmylua_code_analysis/src/vfs/mod.rs, crates/emmylua_ls/src/handlers/fold_range/builder.rs
https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/lifetime_syntax/static.MISMATCHED_LIFETIME_SYNTAXES.html
=> Fix the new mismatched_lifetime_syntaxes warnings added in Rust 1.89

Cargo.lock, crates/emmylua_parser_desc/Cargo.toml, crates/emmylua_parser_desc/src/lang/json/json_lexer.rs, crates/emmylua_parser_desc/src/lang/vimscript/vim_lexer.rs, crates/emmylua_parser_desc/src/md.rs, crates/emmylua_parser_desc/src/ref_target.rs, crates/emmylua_parser_desc/src/rst.rs, crates/emmylua_parser_desc/src/testlib.rs, crates/emmylua_parser_desc/src/util.rs
GTest prints nice diffs, which is useful for debugging. It also allows continuing test even if assertion fails, so you see all failures if several test cases are crammed in a single `#[test]`.
=> Switch `emmylua_parser_desc` to gtest

crates/emmylua_ls/src/context/file_diagnostic.rs, crates/emmylua_ls/src/handlers/initialized/mod.rs
Problem: "Load workspace" progress is updated after finishing,
triggering errors in clients (e.g. Neovim).
(Regression introduced in f7b400c71b80d69873d3286554b2e7fb9180b3b4)
Solution: Correct sequencing of `update_progress` and `finish_progress`.
Also make `finish_progress` message for diagnostics consistent.
=> fix(progress): don't finish before update

crates/emmylua_code_analysis/src/semantic/infer/narrow/var_ref_id.rs
Previously, the function was mistakenly checking equality between a variable and itself (which is always true).
=> fix: proper ref id starts_with() check
